"""empty message

Revision ID: 106e85b90675
Revises: a685636225dc
Create Date: 2024-06-01 15:02:01.452132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106e85b90675'
down_revision = 'a685636225dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('security_level', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'security_level')
    # ### end Alembic commands ###
