"""empty message

Revision ID: 124314482019
Revises: f6044566b4cb
Create Date: 2024-05-13 15:04:38.675991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124314482019'
down_revision = 'f6044566b4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authentication_level', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.add_column('user', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('user', 'password')
    op.drop_column('user', 'authentication_level')
    # ### end Alembic commands ###
