"""empty message

Revision ID: 163b7844d2fc
Revises: 863541fef3ac
Create Date: 2024-06-01 17:33:51.547441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163b7844d2fc'
down_revision = '863541fef3ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'security_level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('security_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
