"""empty message

Revision ID: 863541fef3ac
Revises: 106e85b90675
Create Date: 2024-06-01 17:33:01.453585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863541fef3ac'
down_revision = '106e85b90675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###
